// 4. Alert-notification/alert-notification-demo-vue/src/App.vue
<template>
  <div id="app">
    <h1>Vue alert-notification demo</h1>
    <alert-notification id="notification" message="Hello world!" life="3000">
    <span slot="content">Hello world closes after 3 seconds</span>
    </alert-notification>

    <button onclick="notification.show('danger')">Danger Alert!</button>
    <button onclick="notification.show('success')">Success Alert!</button>
  </div>
</template>

// 4. Alert-notification/alert-notification-demo-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { html, PolymerElement } from '@polymer/polymer/polymer-element.js';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
}

<h1>Angular alert notification demo</h1>

<alert-notification id="notification" message="Hello world!" life="3000">
    <span slot="content">Hello world closes after 3 seconds</span>
</alert-notification>

<button onclick="notification.show('danger')">Danger Alert!</button>
<button onclick="notification.show('success')">Success Alert!</button>
